# Generated by Django 2.1.7 on 2019-03-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('description', models.TextField(verbose_name='decrição')),
                ('icon', models.URLField(verbose_name='icone')),
            ],
            options={
                'verbose_name': 'tema',
                'verbose_name_plural': 'temas',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='talk_ptr',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
