# Generated by Django 2.1.7 on 2019-03-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190304_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(default='', verbose_name='slug'),
        ),
    ]
