# Generated by Django 2.1.7 on 2019-03-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subtitle',
            field=models.CharField(default='', max_length=255, verbose_name='subtítulo'),
        ),
        migrations.AddField(
            model_name='subject',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='titulo'),
        ),
    ]
