# Generated by Django 2.1.7 on 2019-03-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='criado em'),
        ),
    ]
